name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_REGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/your-image-name:latest .
          docker push ${{ secrets.ACR_REGISTRY }}/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to ACI
        uses: Azure/aci-deploy@v1
        with:
          resource-group: your-resource-group
          dns-name-label: your-dns-label
          image: ${{ secrets.ACR_REGISTRY }}/your-image-name:latest
          registry-login-server: ${{ secrets.ACR_REGISTRY }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
