name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.banetaipan }} -p ${{ secrets.dckr_pat_UyFq0EPAzzd2WC7bzNWN9sgdPrs }}

      - name: Build and push Docker image
        run: |
          docker build -t banetaipan/portfolio:V1.0 
          docker push banetaipan/portfolio:V1.0

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Azure
        uses: azure/docker-login@v1
        with:
          login-server: portfolio.azurecr.io
          username: ${{ secrets.portfolio }}
          password: ${{ secrets.dckr_pat_ir8V1ExJxm0Bv1rcm14B0HK9AI4 }}

      - name: Pull and run Docker image from Azure Container Registry
        run: |
          docker pull portfolio.azurecr.io/portfolio:V1.0
          docker run -d -p 80:80 portfolio.azurecr.io/portfolio:V1.0
