name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        # Use 'yarn install --frozen-lockfile' if you are using yarn
        # Use 'pnpm install' if you are using pnpm

      - name: Cypress run
        uses: cypress-io/github-action@v6
